version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm install
  build:
    commands:
      - npm run build

artifacts:
  # Specify the folder where build output is generated
  base-directory: build
  files:
    # Deploy files directly to the root of S3
    - index.html
    - asset-manifest.json
    - static/**/*   # This includes all files in /static folder
