### login
POST http://localhost:8080/login/authenticate HTTP/1.1
Content-Type: application/json

{
    "username": "mcivorsm",
    "password": "PhiDelt2219!"
}

### register
POST http://localhost:8080/user/register HTTP/1.1
Content-Type: application/json

{
    "username": "mcivorsm",
    "password": "PhiDelt2219!",
    "email": "mcivorst@hotmail.com"
}


### register
GET http://localhost:8080/profile HTTP/1.1


### get by id
GET http://localhost:8080/user/username/admin_one HTTP/1.1

### get game by id
GET http://localhost:8080/game/4 HTTP/1.1